version: '3'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    container_name: saya-frontend
    environment:
      - WATCHPACK_POLLING=true
    networks: 
      - mern-stack-networks
    volumes: 
      - ./client:/home/app
    depends_on:
      - backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    container_name: saya-backend
    environment:
      - WATCHPACK_POLLING=true
    networks: 
      - mern-stack-networks
    volumes: 
      - ./server:/home/app
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongoData:/data/db
    container_name: mongo-contianer
    networks: 
      - mern-stack-networks
