name: SAYA CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.13.0'

      - name: Install dependencies
        run: |
          cd client
          npm install
          cd ../server
          npm install

      - name: Build and test frontend
        run: |
          cd client
          npm test
          npm run build

      - name: Build and test backend
        run: |
          cd server
          npm test

      - name: Docker Compose
        run: docker-compose up -d
        working-directory: ${{ github.workspace }}

      - name: Debug Client Directory
        run: |
          cd client
          ls -l
          npm install
          ls -l

