name: SAYA CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd client
          npm install
          cd ../server
          npm install


      - name: Build and test frontend
        run: |
          cd client
          npm run build

      - name: Build and test backend
        run: |
          cd server

      - name: Build Docker image backend
        run: |
          cd server
          docker build -t chinmayi0301/saya-backend .
        working-directory: ${{ github.workspace }}

      - name: Build Docker image frontend
        run: |
          cd client
          docker build -t chinmayi0301/saya-frontend .
        working-directory: ${{ github.workspace }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_ACCESS_TOKEN }}"

      - name: Push Docker image frontend
        run: |
          docker push chinmayi0301/saya-frontend
        working-directory: ${{ github.workspace }}/client
      
      - name: Push Docker image backend
        run: |
          docker push chinmayi0301/saya-backend
        working-directory: ${{ github.workspace }}/server

      - name: Docker Compose
        run: docker-compose up -d
        working-directory: ${{ github.workspace }}

      - name: Debug Client Directory
        run: |
          cd client
          ls -l
          npm install
          ls -l
