name: SAYA CI/CD

on:
  push:
    branches:["master"]
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd client
          npm install
          cd ../server
          npm install

      - name: Build and test frontend
        run: |
          cd client
          npm test
          npm run build

      - name: Build and test backend
        run: |
          cd server
          npm test

      - name: Build Docker image
        run: |
          cd server
          docker build -t dhiksha123/saya-frontend .
        working-directory: ${{ github.workspace }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "${{ secrets.dhiksha123 }}"
          password: "${{ secrets.docker123 }}"

      - name: Push Docker image
        run: |
          docker push your-dockerhub-username/saya-frontend
        working-directory: ${{ github.workspace }}

      - name: Docker Compose
        run: docker-compose up -d
        working-directory: ${{ github.workspace }}

      - name: Debug Client Directory
        run: |
          cd client
          ls -l
          npm install
          ls -l

